# Generated by Django 5.0.6 on 2024-10-03 16:48

import datetime
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('price', models.IntegerField()),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('newVisitId', models.CharField(editable=False, max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emg', models.BooleanField(default=False)),
                ('pay', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=6)),
                ('status', models.CharField(blank=True, default='Created', max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('service', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None)),
                ('patientId', models.CharField(blank=True, editable=False, max_length=100, unique=True)),
                ('refund_status', models.CharField(choices=[('No Refund', 'No Refund'), ('Initiated', 'Initiated'), ('Approval Pending', 'Approval Pending'), ('Approval Done', 'Approval Done'), ('Refunded', 'Refunded')], default='No Refund', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VisitNotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('referrer', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('service_name', models.CharField(max_length=100)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('price', models.IntegerField()),
                ('patientVisit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to='patients.patientvisit')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_patients_visits', to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque'), ('Credit Card', 'Credit Card'), ('Debit Card', 'Debit Card'), ('Google Pay', 'Google Pay'), ('PhonePe', 'PhonePe'), ('Amazon Pay', 'Amazon Pay'), ('Net Banking', 'Net Banking'), ('UPI', 'UPI'), ('Other', 'Other')], default='Cash', max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_mode', models.CharField(max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
            options={
                'db_table': 'payments',
            },
        ),
        migrations.AddField(
            model_name='patientvisit',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_visits', to='patients.visit'),
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('refund', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Unpaid', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('visit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patients.visit')),
            ],
        ),
    ]
